#!/bin/bash

START_TIME_STAMP=`date +%s`

date > controller.log
echo $START_TIME_STAMP >> controller.log

while true
do
	./controller-conn.sh $START_TIME_STAMP 
	#| tee -a controller.log
	sleep 5
	clear
done
